# Generated by Django 4.2 on 2023-04-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo2app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='place1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=250)),
                ('img1', models.ImageField(upload_to='pics1')),
                ('desc2', models.TextField()),
            ],
        ),
    ]
